use crate::imports::*;
use crate::result::Result;
use crate::tx::{generator as native, Fees, PaymentDestination, PaymentOutput, PaymentOutputs, RandomFeeSettings};
use crate::utxo::{TryIntoUtxoEntryReferences, UtxoEntryReference};
use crate::wasm::tx::generator::*;
use crate::wasm::tx::IFees;
// use crate::wasm::wallet::Account;
use crate::wasm::UtxoContext;
use kaspa_addresses::Version;
use kaspa_consensus_core::tx::TransactionOutput;
use kaspa_stealth::{try_create_stealth_output, StealthAddress};
use kaspa_txscript::{pay_to_address_script, pay_to_stealth};

#[wasm_bindgen(typescript_custom_section)]
const TS_GENERATOR_SETTINGS_OBJECT: &'static str = r#"
/**
 * Configuration for the transaction {@link Generator}. This interface
 * allows you to specify UTXO sources, transaction outputs, change address,
 * priority fee, and other transaction parameters.
 * 
 * If the total number of UTXOs needed to satisfy the transaction outputs
 * exceeds maximum allowed number of UTXOs per transaction (limited by
 * the maximum transaction mass), the {@link Generator} will produce 
 * multiple chained transactions to the change address and then used these
 * transactions as a source for the "final" transaction.
 * 
 * @see 
 *      {@link kaspaToSompi},
 *      {@link Generator}, 
 *      {@link PendingTransaction}, 
 *      {@link UtxoContext}, 
 *      {@link UtxoEntry},
 *      {@link createTransactions},
 *      {@link estimateTransactions}
 * @category Wallet SDK
 */
type IGeneratorOutput = IPaymentOutput | IScriptPublicKeyOutput;

/**
 * Output destination specified directly by a {@link ScriptPublicKey}.
 *
 * This is useful for advanced use-cases such as stealth payouts where the caller
 * already constructed the full script (version 16 + 66 bytes), or for custom scripts.
 */
interface IScriptPublicKeyOutput {
    /**
     * Script public key.
     *
     * Can be provided as:
     * - {@link ScriptPublicKey} instance
     * - {@link IScriptPublicKey} object: `{ version, script }`
     * - HexString representing the full ScriptPublicKey encoding (version + script)
     */
    scriptPublicKey: ScriptPublicKey | IScriptPublicKey | HexString;
    /**
     * Output amount in SOMPI.
     */
    amount: bigint;
}

interface IGeneratorSettingsObject {
    /** 
     * Final transaction outputs (do not supply change transaction).
     * 
     * Typical usage:
     * - { address: "kaspa:...", amount: 1000n }
     * - { scriptPublicKey: { version: 16, script: "..." }, amount: 1000n }
     */
    outputs: IGeneratorOutput | IGeneratorOutput[];
    /** 
     * Address to be used for change, if any. 
     */
    changeAddress: Address | string;
    /**
     * Fee rate in SOMPI per 1 gram of mass.
     * 
     * Fee rate is applied to all transactions generated by the {@link Generator}.
     * This includes batch and final transactions. If not set, the fee rate is 
     * not applied.
     */
    feeRate?: number;
    /** 
     * Priority fee in SOMPI.
     * 
     * If supplying `bigint` value, it will be interpreted as a sender-pays fee.
     * Alternatively you can supply an object with `amount` and `source` properties
     * where `source` contains the {@link FeeSource} enum.
     * 
     * **IMPORTANT:* When sending an outbound transaction (transaction that
     * contains outputs), the `priorityFee` must be set, even if it is zero.
     * However, if the transaction is missing outputs (and thus you are
     * creating a compound transaction against your change address),
     * `priorityFee` should not be set (i.e. it should be `undefined`).
     * 
     * @see {@link IFees}, {@link FeeSource}
     */
    priorityFee?: IFees | bigint;
    /**
     * Optional minimum randomization offset (sompi) added to the priority fee.
     */
    feeRandomizationMinSompi?: bigint;
    /**
     * Optional maximum randomization offset (sompi) added to the priority fee.
     */
    feeRandomizationMaxSompi?: bigint;
    /**
     * UTXO entries to be used for the transaction. This can be an
     * array of UtxoEntry instances, objects matching {@link IUtxoEntry}
     * interface, or a {@link UtxoContext} instance.
     */
    entries: IUtxoEntry[] | UtxoEntryReference[] | UtxoContext;
    /**
     * Optional UTXO entries that will be consumed before those available in `entries`.
     * You can use this property to apply custom input selection logic.
     * Please note that these inputs are consumed first, then `entries` are consumed
     * to generate a desirable transaction output amount.  If transaction mass
     * overflows, these inputs will be consumed into a batch/sweep transaction
     * where the destination if the `changeAddress`.
     */
    priorityEntries?: IUtxoEntry[] | UtxoEntryReference[],
    /**
     * Optional number of signature operations in the transaction.
     */
    sigOpCount?: number;
    /**
     * Optional minimum number of signatures required for the transaction.
     */
    minimumSignatures?: number;
    /**
     * Optional data payload to be included in the transaction.
     */
    payload?: Uint8Array | HexString;

    /**
     * Optional NetworkId or network id as string (i.e. `mainnet` or `testnet-11`). Required when {@link IGeneratorSettingsObject.entries} is array
     */
    networkId?: NetworkId | string
}
"#;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(extends = Object, typescript_type = "IGeneratorSettingsObject")]
    #[derive(Clone, Debug, PartialEq, Eq)]
    pub type IGeneratorSettingsObject;
}

/// Generator is a type capable of generating transactions based on a supplied
/// set of UTXO entries or a UTXO entry producer (such as {@link UtxoContext}). The Generator
/// accumulates UTXO entries until it can generate a transaction that meets the
/// requested amount or until the total mass of created inputs exceeds the allowed
/// transaction mass, at which point it will produce a compound transaction by forwarding
/// all selected UTXO entries to the supplied change address and prepare to start generating
/// a new transaction.  Such sequence of daisy-chained transactions is known as a "batch".
/// Each compound transaction results in a new UTXO, which is immediately reused in the
/// subsequent transaction.
///
/// The Generator constructor accepts a single {@link IGeneratorSettingsObject} object.
///
/// ```javascript
///
/// let generator = new Generator({
///     utxoEntries : [...],
///     changeAddress : "kaspa:...",
///     outputs : [
///         { amount : kaspaToSompi(10.0), address: "kaspa:..."},
///         { amount : kaspaToSompi(20.0), address: "kaspa:..."},
///         ...
///     ],
///     priorityFee : 1000n,
/// });
///
/// let pendingTransaction;
/// while(pendingTransaction = await generator.next()) {
///     await pendingTransaction.sign(privateKeys);
///     await pendingTransaction.submit(rpc);
/// }
///
/// let summary = generator.summary();
/// console.log(summary);
///
/// ```
/// @see
///     {@link IGeneratorSettingsObject},
///     {@link PendingTransaction},
///     {@link UtxoContext},
///     {@link createTransactions},
///     {@link estimateTransactions},
/// @category Wallet SDK
#[wasm_bindgen]
pub struct Generator {
    inner: Arc<native::Generator>,
}

#[wasm_bindgen]
impl Generator {
    #[wasm_bindgen(constructor)]
    pub fn ctor(args: IGeneratorSettingsObject) -> Result<Generator> {
        let settings = GeneratorSettings::try_from(args)?;

        let GeneratorSettings {
            network_id,
            source,
            priority_utxo_entries,
            multiplexer,
            final_transaction_destination,
            final_transaction_outputs,
            change_address,
            fee_rate,
            final_priority_fee,
            fee_randomization,
            sig_op_count,
            minimum_signatures,
            payload,
        } = settings;

        let settings = match source {
            GeneratorSource::UtxoEntries(utxo_entries) => {
                let change_address = change_address
                    .ok_or_else(|| Error::custom("changeAddress is required for Generator constructor with UTXO entries"))?;

                let network_id =
                    network_id.ok_or_else(|| Error::custom("networkId is required for Generator constructor with UTXO entries"))?;

                native::GeneratorSettings::try_new_with_iterator(
                    network_id,
                    Box::new(utxo_entries.into_iter()),
                    priority_utxo_entries,
                    change_address,
                    sig_op_count,
                    minimum_signatures,
                    final_transaction_destination,
                    fee_rate,
                    final_priority_fee,
                    payload,
                    multiplexer,
                    fee_randomization,
                )?
            }
            GeneratorSource::UtxoContext(utxo_context) => {
                let change_address = change_address
                    .ok_or_else(|| Error::custom("changeAddress is required for Generator constructor with UTXO entries"))?;

                native::GeneratorSettings::try_new_with_context(
                    utxo_context.into(),
                    priority_utxo_entries,
                    change_address,
                    sig_op_count,
                    minimum_signatures,
                    final_transaction_destination,
                    fee_rate,
                    final_priority_fee,
                    payload,
                    multiplexer,
                    fee_randomization,
                )?
            } // GeneratorSource::Account(account) => {
              //     let account: Arc<dyn crate::account::Account> = account.into();
              //     native::GeneratorSettings::try_new_with_account(account, final_transaction_destination, final_priority_fee, None)?
              // }
        };

        let settings =
            if let Some(outputs) = final_transaction_outputs { settings.with_final_transaction_outputs(outputs) } else { settings };

        let abortable = Abortable::default();
        let generator = native::Generator::try_new(settings, None, Some(&abortable))?;

        Ok(Self { inner: Arc::new(generator) })
    }

    /// Generate next transaction
    pub async fn next(&self) -> Result<JsValue> {
        if let Some(transaction) = self.inner.generate_transaction().transpose() {
            let transaction = PendingTransaction::from(transaction?);
            Ok(transaction.into())
        } else {
            Ok(JsValue::NULL)
        }
    }

    pub async fn estimate(&self) -> Result<GeneratorSummary> {
        let mut stream = self.inner.stream();
        while stream.try_next().await?.is_some() {}
        Ok(self.summary())
    }

    pub fn summary(&self) -> GeneratorSummary {
        self.inner.summary().into()
    }
}

impl Generator {
    pub fn iter(&self) -> impl Iterator<Item = Result<native::PendingTransaction>> {
        self.inner.iter()
    }

    pub fn stream(&self) -> impl Stream<Item = Result<native::PendingTransaction>> {
        self.inner.stream()
    }
}

enum GeneratorSource {
    UtxoEntries(Vec<UtxoEntryReference>),
    UtxoContext(UtxoContext),
    // #[cfg(any(feature = "wasm32-sdk"), not(target_arch = "wasm32"))]
    // Account(Account),
}

/// Converts [`IGeneratorSettingsObject`] to a series of properties intended for use by the [`Generator`].
struct GeneratorSettings {
    pub network_id: Option<NetworkId>,
    pub source: GeneratorSource,
    pub priority_utxo_entries: Option<Vec<UtxoEntryReference>>,
    pub multiplexer: Option<Multiplexer<Box<Events>>>,
    pub final_transaction_destination: PaymentDestination,
    pub final_transaction_outputs: Option<Vec<TransactionOutput>>,
    pub change_address: Option<Address>,
    pub fee_rate: Option<f64>,
    pub final_priority_fee: Fees,
    pub fee_randomization: Option<RandomFeeSettings>,
    pub sig_op_count: u8,
    pub minimum_signatures: u16,
    pub payload: Option<Vec<u8>>,
}

impl TryFrom<IGeneratorSettingsObject> for GeneratorSettings {
    type Error = Error;
    fn try_from(args: IGeneratorSettingsObject) -> std::result::Result<Self, Self::Error> {
        let network_id = args.try_get::<NetworkId>("networkId")?;

        // lack of outputs results in a sweep transaction compounding utxos into the change address
        let outputs = args.get_value("outputs")?;
        let (final_transaction_destination, final_transaction_outputs) = if outputs.is_undefined() {
            (PaymentDestination::Change, None)
        } else if let Ok(payment_outputs) = PaymentOutputs::try_owned_from(outputs.clone()) {
            (payment_outputs.into(), None)
        } else {
            let tx_outputs = generator_outputs_to_transaction_outputs(outputs)?;
            (PaymentDestination::PaymentOutputs(PaymentOutputs { outputs: vec![] }), Some(tx_outputs))
        };

        let change_address = args.try_cast_into::<Address>("changeAddress")?;

        let fee_rate = args.get_f64("feeRate").ok().and_then(|v| (v.is_finite() && !v.is_nan() && v >= 1e-8).then_some(v));

        let final_priority_fee = args.get::<IFees>("priorityFee")?.try_into()?;
        let fee_randomization_min = js_value_to_optional_u64(args.get_value("feeRandomizationMinSompi")?, "feeRandomizationMinSompi")?;
        let fee_randomization_max = js_value_to_optional_u64(args.get_value("feeRandomizationMaxSompi")?, "feeRandomizationMaxSompi")?;
        let fee_randomization = build_fee_randomization(fee_randomization_min, fee_randomization_max)?;

        let generator_source = if let Ok(Some(context)) = args.try_cast_into::<UtxoContext>("entries") {
            GeneratorSource::UtxoContext(context)
        } else if let Some(utxo_entries) = args.try_get_value("entries")? {
            GeneratorSource::UtxoEntries(utxo_entries.try_into_utxo_entry_references()?)
        } else {
            return Err(Error::custom("'entries' property is required for Generator"));
        };

        let priority_utxo_entries = args.try_get_value("priorityEntries")?.map(|v| v.try_into_utxo_entry_references()).transpose()?;

        let sig_op_count = args.get_value("sigOpCount")?;
        let sig_op_count = if sig_op_count.is_undefined() {
            1
        } else {
            let v = js_value_to_optional_u64(sig_op_count, "sigOpCount")?
                .ok_or_else(|| Error::InvalidArgument("sigOpCount is required".into()))?;
            u8::try_from(v).map_err(|_| Error::InvalidArgument(format!("sigOpCount must be <= {}", u8::MAX)))?
        };

        let minimum_signatures = args.get_value("minimumSignatures")?;
        let minimum_signatures = if minimum_signatures.is_undefined() {
            1
        } else {
            let v = js_value_to_optional_u64(minimum_signatures, "minimumSignatures")?
                .ok_or_else(|| Error::InvalidArgument("minimumSignatures is required".into()))?;
            u16::try_from(v).map_err(|_| Error::InvalidArgument(format!("minimumSignatures must be <= {}", u16::MAX)))?
        };

        let payload = args.get_vec_u8("payload").ok();

        let settings = GeneratorSettings {
            network_id,
            source: generator_source,
            priority_utxo_entries,
            multiplexer: None,
            final_transaction_destination,
            final_transaction_outputs,
            change_address,
            fee_rate,
            final_priority_fee,
            fee_randomization,
            sig_op_count,
            minimum_signatures,
            payload,
        };

        Ok(settings)
    }
}

fn generator_outputs_to_transaction_outputs(outputs: JsValue) -> Result<Vec<TransactionOutput>> {
    let mut tx_outputs = Vec::new();

    let iter = js_sys::try_iter(&outputs)?;
    if let Some(iter) = iter {
        for item in iter {
            let value = item?;
            tx_outputs.push(generator_output_to_transaction_output(value)?);
        }
    } else {
        // `outputs` may be a single output object instead of an array.
        tx_outputs.push(generator_output_to_transaction_output(outputs)?);
    }

    Ok(tx_outputs)
}

fn generator_output_to_transaction_output(value: JsValue) -> Result<TransactionOutput> {
    // Prefer address-based outputs for backwards compatibility.
    if let Ok(output) = PaymentOutput::try_owned_from(value.clone()) {
        let script_public_key = if output.address.version == Version::Stealth {
            let stealth_addr = StealthAddress::try_from_slice(&output.address.payload)
                .map_err(|_| Error::custom("Invalid stealth address payload"))?;
            let ephemeral_output = try_create_stealth_output(&stealth_addr)
                .map_err(|e| Error::custom(format!("Failed to create stealth output: {e}")))?;
            pay_to_stealth(&ephemeral_output)
        } else {
            pay_to_address_script(&output.address).map_err(|e| Error::custom(e.to_string()))?
        };
        return Ok(TransactionOutput::new(output.amount, script_public_key));
    }

    let object = Object::try_from(&value).ok_or_else(|| Error::custom("Invalid output: expected an object"))?;

    let spk_value = object.get_value("scriptPublicKey")?;
    if spk_value.is_null() || spk_value.is_undefined() {
        return Err(Error::custom("Invalid output: missing 'address' or 'scriptPublicKey'"));
    }

    let script_public_key = ScriptPublicKey::try_owned_from(spk_value)?;

    let amount_value = object.get_value("amount")?;
    let amount = if amount_value.is_null() || amount_value.is_undefined() {
        let value_value = object.get_value("value")?;
        js_value_to_optional_u64(value_value, "value")?.ok_or_else(|| Error::InvalidArgument("value is required".into()))?
    } else {
        js_value_to_optional_u64(amount_value, "amount")?.ok_or_else(|| Error::InvalidArgument("amount is required".into()))?
    };

    Ok(TransactionOutput::new(amount, script_public_key))
}

const JS_MAX_SAFE_INTEGER: f64 = 9_007_199_254_740_991.0; // 2^53 - 1

fn f64_to_u64_safe_integer(num: f64, field: &str) -> Result<u64> {
    if !num.is_finite() {
        return Err(Error::InvalidArgument(format!("{field} must be a finite number")));
    }
    if num < 0.0 {
        return Err(Error::InvalidArgument(format!("{field} must be non-negative")));
    }
    if num.fract() != 0.0 {
        return Err(Error::InvalidArgument(format!("{field} must be an integer")));
    }
    if num > JS_MAX_SAFE_INTEGER {
        return Err(Error::InvalidArgument(format!("{field} exceeds JS MAX_SAFE_INTEGER")));
    }

    Ok(num as u64)
}

fn js_value_to_optional_u64(value: JsValue, field: &str) -> Result<Option<u64>> {
    if value.is_null() || value.is_undefined() {
        return Ok(None);
    }

    if value.is_bigint() {
        let big_int: js_sys::BigInt = value.unchecked_into();
        let v: u64 =
            big_int.try_into().map_err(|v| Error::InvalidArgument(format!("{field}: unable to convert BigInt value {v:?}")))?;
        return Ok(Some(v));
    }

    if let Some(num) = value.as_f64() {
        return Ok(Some(f64_to_u64_safe_integer(num, field)?));
    }

    Err(Error::InvalidArgument(format!("{field} must be a number or bigint")))
}

fn build_fee_randomization(min: Option<u64>, max: Option<u64>) -> Result<Option<RandomFeeSettings>> {
    match (min, max) {
        (None, None) => Ok(None),
        (Some(min), Some(max)) => {
            let settings = RandomFeeSettings { enabled: true, min_sompi: min, max_sompi: max };
            settings.validate()?;
            Ok(Some(settings))
        }
        _ => Err(Error::InvalidArgument("feeRandomizationMinSompi and feeRandomizationMaxSompi must both be provided".to_string())),
    }
}
