#!/bin/bash
set -e

# Workaround for Rust 1.87.0
# https://github.com/rust-lang/rust/issues/141048
#
# wasm-pack uses wasm-bindgen with --weak-refs. This requires reference-types
# to be enabled in the generated wasm module.
export RUSTFLAGS='-Ctarget-cpu=mvp -Ctarget-feature=+reference-types --cfg getrandom_backend="wasm_js"'

wasm-pack build --weak-refs --target nodejs --out-name kaspa --out-dir nodejs/kaspa --features wasm32-sdk
