# ---------------------------------------- Chef image -------------------------------------------
FROM rust:alpine AS chef
RUN apk --no-cache add \
  musl-dev \
  protobuf-dev \
  g++ \
  clang18-dev \
  linux-headers \
  openssl-dev
RUN cargo install cargo-chef --locked
WORKDIR /app

# ---------------------------------------- Planner image ----------------------------------------
FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

# ---------------------------------------- Builder image ----------------------------------------
FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json

ENV RUSTFLAGS="-C target-feature=-crt-static" \
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL="sparse"

# Build dependencies - this is the caching Docker layer
RUN cargo chef cook --release --recipe-path recipe.json -p miner-agent

COPY . .
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git,sharing=locked \
    --mount=type=cache,id=cargo-target,target=/app/target,sharing=locked \
    cargo build --release --bin miner-agent \
    && cp /app/target/release/miner-agent /app/miner-agent

# ---------------------------------------- Runtime image ----------------------------------------
FROM alpine:3.21 AS runtime
WORKDIR /app

RUN apk --no-cache add \
  libgcc \
  libstdc++ \
  tini \
  ca-certificates

# Create non-root user for security
RUN addgroup -g 1000 app && adduser -u 1000 -G app -h /app -D app

COPY --from=builder /app/miner-agent .

RUN chown -R app:app /app

USER app
ENTRYPOINT [ "/sbin/tini", "--" ]
CMD [ "/app/miner-agent" ]
