name: wallet_widgets
description: Wallet-specific UI widgets
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  design_system:
  wallet_domain:
  qr_flutter: ^4.1.0

flutter:
  uses-material-design: true
