name: kaspa_wallet_extension
description: Kaspa Wallet Chrome Extension
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
