//!
//! Pending transaction encapsulating a
//! transaction generated by the [`Generator`].
//!
#![allow(unused_imports)]

use crate::imports::*;
use crate::result::Result;
use crate::rpc::DynRpcApi;
use crate::tx::generator::stealth_change::PendingStealthChange;
use crate::tx::{DataKind, Generator, MAXIMUM_STANDARD_TRANSACTION_MASS};
use crate::utxo::{UtxoContext, UtxoEntryId, UtxoEntryReference, UtxoIterator};
use kaspa_consensus_core::hashing::sighash_type::SigHashType;
use kaspa_consensus_core::sign::{sign_input, sign_with_multiple_v2, Signed};
use kaspa_consensus_core::tx::{SignableTransaction, Transaction, TransactionId, TransactionInput, TransactionOutput};
use kaspa_rpc_core::{RpcTransaction, RpcTransactionId};

pub(crate) struct PendingTransactionInner {
    /// Generator that produced the transaction
    pub(crate) generator: Generator,
    /// UtxoEntryReferences of the pending transaction
    pub(crate) utxo_entries: AHashMap<UtxoEntryId, UtxoEntryReference>,
    /// Transaction Id (cached in pending to avoid mutex lock)
    pub(crate) id: TransactionId,
    /// Signable transaction (actual transaction that will be signed and sent)
    pub(crate) signable_tx: Mutex<SignableTransaction>,
    /// UTXO addresses used by this transaction
    pub(crate) addresses: Vec<Address>,
    /// Whether the transaction has been committed to the mempool via RPC
    pub(crate) is_submitted: AtomicBool,
    /// Payment value of the transaction (transaction destination amount)
    pub(crate) payment_value: Option<u64>,
    /// The index (position) of the change output in the transaction
    pub(crate) change_output_index: Option<usize>,
    /// Change value of the transaction (transaction change amount)
    pub(crate) change_output_value: u64,
    /// Total aggregate value of all inputs
    pub(crate) aggregate_input_value: u64,
    /// Total aggregate value of all outputs
    pub(crate) aggregate_output_value: u64,
    /// Minimum number of signatures required for the transaction
    /// (passed in during transaction creation). This value is used
    /// to estimate the mass of the transaction.
    pub(crate) minimum_signatures: u16,
    // Transaction mass
    pub(crate) mass: u64,
    /// Fees of the transaction
    pub(crate) fees: u64,
    /// Indicates the type of the transaction
    pub(crate) kind: DataKind,
    /// Pre-calculated stealth change key data (if change is to stealth address).
    /// This allows the caller to store the spending key immediately after
    /// transaction submission, without needing to re-scan the blockchain.
    pub(crate) stealth_change: Mutex<Option<PendingStealthChange>>,
}

impl std::fmt::Debug for PendingTransaction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let transaction = self.transaction();
        f.debug_struct("PendingTransaction")
            .field("utxo_entries", &self.inner.utxo_entries)
            .field("addresses", &self.inner.addresses)
            .field("payment_value", &self.inner.payment_value)
            .field("change_output_index", &self.inner.change_output_index)
            .field("change_output_value", &self.inner.change_output_value)
            .field("aggregate_input_value", &self.inner.aggregate_input_value)
            .field("minimum_signatures", &self.inner.minimum_signatures)
            .field("mass", &self.inner.mass)
            .field("fees", &self.inner.fees)
            .field("kind", &self.inner.kind)
            .field("transaction", &transaction)
            .finish()
    }
}

/// Meta transaction encapsulating a transaction generated by the [`Generator`].
/// Contains auxiliary information about the transaction such as aggregate
/// input/output amounts, fees, etc.
#[derive(Clone)]
pub struct PendingTransaction {
    pub(crate) inner: Arc<PendingTransactionInner>,
}

impl PendingTransaction {
    #[allow(clippy::too_many_arguments)]
    pub fn try_new(
        generator: &Generator,
        transaction: Transaction,
        utxo_entries: Vec<UtxoEntryReference>,
        addresses: Vec<Address>,
        payment_value: Option<u64>,
        change_output_index: Option<usize>,
        change_output_value: u64,
        aggregate_input_value: u64,
        aggregate_output_value: u64,
        minimum_signatures: u16,
        mass: u64,
        fees: u64,
        kind: DataKind,
    ) -> Result<Self> {
        let id = transaction.id();
        let entries = utxo_entries.iter().map(|e| e.utxo.as_ref().into()).collect::<Vec<_>>();
        let signable_tx = Mutex::new(SignableTransaction::with_entries(transaction, entries));
        let utxo_entries = utxo_entries.into_iter().map(|entry| (entry.id(), entry)).collect::<AHashMap<_, _>>();
        Ok(Self {
            inner: Arc::new(PendingTransactionInner {
                generator: generator.clone(),
                id,
                signable_tx,
                utxo_entries,
                addresses,
                is_submitted: AtomicBool::new(false),
                payment_value,
                change_output_index,
                change_output_value,
                aggregate_input_value,
                aggregate_output_value,
                minimum_signatures,
                mass,
                fees,
                kind,
                stealth_change: Mutex::new(None),
            }),
        })
    }

    /// Sets the pre-calculated stealth change data for this transaction.
    ///
    /// This should be called by the Generator after creating a stealth change output.
    /// The data will be stored until the transaction is submitted, at which point
    /// it can be retrieved via [`take_stealth_change`] for permanent storage.
    pub fn set_stealth_change(&self, pending: PendingStealthChange) {
        *self.inner.stealth_change.lock().unwrap() = Some(pending);
    }

    /// Returns a reference to the stealth change data if present.
    pub fn stealth_change(&self) -> Option<PendingStealthChange> {
        self.inner.stealth_change.lock().unwrap().clone()
    }

    /// Takes the stealth change data, leaving None in its place.
    ///
    /// This should be called after the transaction is successfully submitted
    /// to retrieve the pre-calculated key data for permanent storage.
    pub fn take_stealth_change(&self) -> Option<PendingStealthChange> {
        self.inner.stealth_change.lock().unwrap().take()
    }

    pub fn id(&self) -> TransactionId {
        self.inner.id
    }

    pub fn generator(&self) -> &Generator {
        &self.inner.generator
    }

    pub fn source_utxo_context(&self) -> &Option<UtxoContext> {
        self.inner.generator.source_utxo_context()
    }

    pub fn destination_utxo_context(&self) -> &Option<UtxoContext> {
        self.inner.generator.destination_utxo_context()
    }

    /// Addresses used by the pending transaction
    pub fn addresses(&self) -> &Vec<Address> {
        &self.inner.addresses
    }

    /// Get UTXO entries [`AHashSet<UtxoEntryReference>`] of the pending transaction
    pub fn utxo_entries(&self) -> &AHashMap<UtxoEntryId, UtxoEntryReference> {
        &self.inner.utxo_entries
    }

    pub fn fees(&self) -> u64 {
        self.inner.fees
    }

    pub fn mass(&self) -> u64 {
        self.inner.mass
    }

    pub fn minimum_signatures(&self) -> u16 {
        self.inner.minimum_signatures
    }

    pub fn aggregate_input_value(&self) -> u64 {
        self.inner.aggregate_input_value
    }

    pub fn aggregate_output_value(&self) -> u64 {
        self.inner.aggregate_output_value
    }

    pub fn payment_value(&self) -> Option<u64> {
        self.inner.payment_value
    }

    pub fn change_output_index(&self) -> Option<usize> {
        self.inner.change_output_index
    }

    pub fn change_value(&self) -> u64 {
        self.inner.change_output_value
    }

    pub fn is_final(&self) -> bool {
        self.inner.kind.is_final()
    }

    pub fn is_batch(&self) -> bool {
        !self.inner.kind.is_final()
    }

    pub fn network_type(&self) -> NetworkType {
        self.inner.generator.network_type()
    }

    pub fn transaction(&self) -> Transaction {
        self.inner.signable_tx.lock().unwrap().tx.clone()
    }

    pub fn signable_transaction(&self) -> SignableTransaction {
        self.inner.signable_tx.lock().unwrap().clone()
    }

    pub fn rpc_transaction(&self) -> RpcTransaction {
        self.inner.signable_tx.lock().unwrap().tx.as_ref().into()
    }

    /// Submit the transaction on the supplied rpc
    pub async fn try_submit(&self, rpc: &Arc<DynRpcApi>) -> Result<RpcTransactionId> {
        // Sanity check to prevent multiple invocations (for API use).
        // This is intentionally one-shot even if the first attempt fails, to prevent accidental double-submits.
        if self.inner.is_submitted.swap(true, Ordering::SeqCst) {
            return Err(Error::Custom("PendingTransaction::try_submit() called multiple times".to_string()));
        }

        let rpc_transaction: RpcTransaction = self.rpc_transaction();

        // if we are running under UtxoProcessor
        if let Some(utxo_context) = self.inner.generator.source_utxo_context() {
            // lock UtxoProcessor notification ingest
            let _lock = utxo_context.processor().notification_lock().await;

            // register pending UTXOs with UtxoProcessor
            utxo_context.register_outgoing_transaction(self).await?;

            // try to submit transaction
            match rpc.submit_transaction(rpc_transaction, false).await {
                Ok(id) => {
                    // on successful submit, create a notification
                    utxo_context.notify_outgoing_transaction(self).await?;
                    Ok(id)
                }
                Err(error) => {
                    // in case of failure, remove transaction UTXOs from the consumed list
                    utxo_context.cancel_outgoing_transaction(self).await?;
                    Err(error.into())
                }
            }
        } else {
            // No UtxoProcessor present (API etc)
            Ok(rpc.submit_transaction(rpc_transaction, false).await?)
        }
    }

    pub async fn log(&self) -> Result<()> {
        log_info!("pending transaction: {:?}", self.rpc_transaction());
        Ok(())
    }

    /// Signs regular (non-stealth) inputs using the standard signer.
    /// If the transaction has stealth inputs, they will remain unsigned.
    pub fn try_sign(&self) -> Result<()> {
        let signer = self.inner.generator.signer().as_ref().ok_or_else(|| Error::Custom("no signer in tx generator".to_string()))?;
        // If transaction has stealth inputs, use partial signing (stealth inputs will be signed separately)
        let has_stealth = self.has_stealth_inputs();
        let signed_tx = signer.try_sign_partial(self.inner.signable_tx.lock()?.clone(), self.addresses(), !has_stealth)?;
        *self.inner.signable_tx.lock()? = signed_tx;
        Ok(())
    }

    /// Signs stealth inputs using the provided signer.
    ///
    /// This should be called in addition to try_sign() when the
    /// transaction contains stealth inputs.
    pub async fn try_sign_stealth(&self, signer: &super::stealth_signer::StealthSigner) -> Result<()> {
        let signable_tx = self.inner.signable_tx.lock()?.clone();
        let include = self.inner.generator.include_delegation_id();
        let signed = signer.sign(signable_tx, include).await?;
        *self.inner.signable_tx.lock()? = signed.unwrap();
        Ok(())
    }

    /// Checks if this transaction has any stealth inputs.
    ///
    /// Stealth inputs are identified by their script version (STEALTH_SCRIPT_VERSION = 16).
    pub fn has_stealth_inputs(&self) -> bool {
        use kaspa_txscript::STEALTH_SCRIPT_VERSION;

        let signable_tx = match self.inner.signable_tx.lock() {
            Ok(tx) => tx,
            Err(_) => return false,
        };

        signable_tx
            .entries
            .iter()
            .any(|entry| entry.as_ref().map(|e| e.script_public_key.version() == STEALTH_SCRIPT_VERSION).unwrap_or(false))
    }

    /// Checks if this transaction has any non-stealth inputs.
    ///
    /// Non-stealth inputs are identified by a script version that differs from STEALTH_SCRIPT_VERSION.
    pub fn has_non_stealth_inputs(&self) -> bool {
        use kaspa_txscript::STEALTH_SCRIPT_VERSION;

        let signable_tx = match self.inner.signable_tx.lock() {
            Ok(tx) => tx,
            Err(_) => return false,
        };

        signable_tx
            .entries
            .iter()
            .any(|entry| entry.as_ref().map(|e| e.script_public_key.version() != STEALTH_SCRIPT_VERSION).unwrap_or(false))
    }

    /// Checks if stealth and non-stealth inputs are mixed in the same transaction.
    pub fn has_mixed_stealth_and_legacy_inputs(&self) -> bool {
        self.has_stealth_inputs() && self.has_non_stealth_inputs()
    }

    /// Enforces that a transaction does not mix stealth and legacy inputs.
    pub fn enforce_stealth_only_inputs(&self) -> Result<()> {
        if self.has_mixed_stealth_and_legacy_inputs() {
            return Err(Error::MixedStealthAndLegacyInputsNotAllowed);
        }
        Ok(())
    }

    /// Combined signing method that handles both regular and stealth inputs.
    ///
    /// This is a convenience method that:
    /// 1. Signs all regular inputs using the standard signer
    /// 2. If stealth inputs are present and a stealth_signer is provided, signs those too
    pub async fn try_sign_with_stealth(&self, stealth_signer: Option<&super::stealth_signer::StealthSigner>) -> Result<()> {
        // First, sign with regular signer
        self.try_sign()?;

        // Then, sign stealth inputs if any
        if self.has_stealth_inputs() {
            if let Some(signer) = stealth_signer {
                self.try_sign_stealth(signer).await?;
            } else {
                return Err(Error::Custom("Transaction has stealth inputs but no stealth signer provided".to_string()));
            }
        }

        Ok(())
    }

    pub fn create_input_signature(&self, input_index: usize, private_key: &[u8; 32], hash_type: SigHashType) -> Result<Vec<u8>> {
        let mutable_tx = self.inner.signable_tx.lock()?.clone();
        let verifiable_tx = mutable_tx.as_verifiable();

        Ok(sign_input(&verifiable_tx, input_index, private_key, hash_type))
    }

    pub fn fill_input(&self, input_index: usize, signature_script: Vec<u8>) -> Result<()> {
        let mut mutable_tx = self.inner.signable_tx.lock()?.clone();
        mutable_tx.tx.inputs[input_index].signature_script = signature_script;
        *self.inner.signable_tx.lock().unwrap() = mutable_tx;

        Ok(())
    }

    pub fn sign_input(&self, input_index: usize, private_key: &[u8; 32], hash_type: SigHashType) -> Result<()> {
        let mut mutable_tx = self.inner.signable_tx.lock()?.clone();

        let signature_script = {
            let verifiable_tx = &mutable_tx.as_verifiable();
            sign_input(verifiable_tx, input_index, private_key, hash_type)
        };

        mutable_tx.tx.inputs[input_index].signature_script = signature_script;
        *self.inner.signable_tx.lock().unwrap() = mutable_tx;

        Ok(())
    }

    pub fn try_sign_with_keys(&self, privkeys: &[[u8; 32]], check_fully_signed: Option<bool>) -> Result<()> {
        let mutable_tx = self.inner.signable_tx.lock()?.clone();
        let signed = sign_with_multiple_v2(mutable_tx, privkeys);

        let signed_tx = match signed {
            Signed::Fully(tx) => tx,
            Signed::Partially(_) => {
                if check_fully_signed.unwrap_or(true) {
                    signed.fully_signed()?
                } else {
                    signed.unwrap()
                }
            }
        };

        *self.inner.signable_tx.lock().unwrap() = signed_tx;
        Ok(())
    }

    /*

    WIP: handling RBF within the Wallet infrastructure

    pub fn increase_fees_for_rbf(&self, additional_fees: u64) -> Result<PendingTransaction> {
        #![allow(unused_mut)]
        #![allow(unused_variables)]

        let PendingTransactionInner {
            generator,
            utxo_entries,
            id,
            signable_tx,
            addresses,
            is_submitted,
            payment_value,
            change_output_index,
            change_output_value,
            aggregate_input_value,
            aggregate_output_value,
            minimum_signatures,
            mass,
            fees,
            kind,
        } = &*self.inner;

        let generator = generator.clone();
        let utxo_entries = utxo_entries.clone();
        let id = *id;
        // let signable_tx = Mutex::new(signable_tx.lock()?.clone());
        let mut signable_tx = signable_tx.lock()?.clone();
        let addresses = addresses.clone();
        let is_submitted = AtomicBool::new(false);
        let payment_value = *payment_value;
        let mut change_output_index = *change_output_index;
        let mut change_output_value = *change_output_value;
        let mut aggregate_input_value = *aggregate_input_value;
        let mut aggregate_output_value = *aggregate_output_value;
        let minimum_signatures = *minimum_signatures;
        let mass = *mass;
        let fees = *fees;
        let kind = *kind;

        #[allow(clippy::single_match)]
        match kind {
            DataKind::Final => {
                // change output has sufficient amount to cover fee increase
                // if change_output_value > fee_increase && change_output_index.is_some() {
                if let (Some(index), true) = (change_output_index, change_output_value >= additional_fees) {
                    change_output_value -= additional_fees;
                    if generator.mass_calculator().is_dust(change_output_value) {
                        aggregate_output_value -= change_output_value;
                        signable_tx.tx.outputs.remove(index);
                        change_output_index = None;
                        change_output_value = 0;
                    } else {
                        signable_tx.tx.outputs[index].value = change_output_value;
                    }
                } else {
                    // we need more utxos...
                    let mut utxo_entries_rbf = vec![];
                    let mut available = change_output_value;

                    let utxo_context = generator.source_utxo_context().as_ref().ok_or(Error::custom("No utxo context"))?;
                    let mut context_utxo_entries = UtxoIterator::new(utxo_context);
                    while available < additional_fees {
                        // let utxo_entry = utxo_entries.next().ok_or(Error::InsufficientFunds { additional_needed: additional_fees - available, origin: "increase_fees_for_rbf" })?;
                        // let utxo_entry = generator.get_utxo_entry_for_rbf()?;
                        if let Some(utxo_entry) = context_utxo_entries.next() {
                            // let utxo = utxo_entry.utxo.as_ref();
                            let value = utxo_entry.amount();
                            available += value;
                            // aggregate_input_value += value;

                            utxo_entries_rbf.push(utxo_entry);
                            // signable_tx.lock().unwrap().tx.inputs.push(utxo.as_input());
                        } else {
                            // generator.stash(utxo_entries_rbf);
                            // utxo_entries_rbf.into_iter().for_each(|utxo_entry|generator.stash(utxo_entry));
                            return Err(Error::InsufficientFunds {
                                additional_needed: additional_fees - available,
                                origin: "increase_fees_for_rbf",
                            });
                        }
                    }

                    let utxo_entries_vec = utxo_entries
                        .iter()
                        .map(|(_, utxo_entry)| utxo_entry.as_ref().clone())
                        .chain(utxo_entries_rbf.iter().map(|utxo_entry| utxo_entry.as_ref().clone()))
                        .collect::<Vec<_>>();

                    let inputs = utxo_entries_rbf
                        .into_iter()
                        .map(|utxo| TransactionInput::new(utxo.outpoint().clone().into(), vec![], 0, generator.sig_op_count()));

                    signable_tx.tx.inputs.extend(inputs);

                    // let transaction_mass = generator.mass_calculator().calc_overall_mass_for_unsigned_consensus_transaction(
                    //     &signable_tx.tx,
                    //     &utxo_entries_vec,
                    //     self.inner.minimum_signatures,
                    // )?;
                    // if transaction_mass > MAXIMUM_STANDARD_TRANSACTION_MASS {
                    //     // this should never occur as we should not produce transactions higher than the mass limit
                    //     return Err(Error::MassCalculationError);
                    // }
                    // signable_tx.tx.set_mass(transaction_mass);

                    // utxo

                    // let input = ;
                }
            }
            _ => {}
        }

        let inner = PendingTransactionInner {
            generator,
            utxo_entries,
            id,
            signable_tx: Mutex::new(signable_tx),
            addresses,
            is_submitted,
            payment_value,
            change_output_index,
            change_output_value,
            aggregate_input_value,
            aggregate_output_value,
            minimum_signatures,
            mass,
            fees,
            kind,
        };

        Ok(PendingTransaction { inner: Arc::new(inner) })

        // let mut mutable_tx = self.inner.signable_tx.lock()?.clone();
        // mutable_tx.tx.fee += fees;
        // *self.inner.signable_tx.lock().unwrap() = mutable_tx;
    }
    */
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tests::RpcCoreMock;
    use crate::tx::generator::test::{change_address, make_generator, output_address};
    use crate::tx::{Fees, PaymentOutput};

    #[cfg(not(target_arch = "wasm32"))]
    #[tokio::test]
    async fn try_submit_twice_returns_error_instead_of_panicking() -> Result<()> {
        let network_id = NetworkId::with_suffix(NetworkType::Testnet, 10);
        let payment_output = PaymentOutput::new(output_address(network_id.into()), crate::utils::kaspa_to_sompi(1.0));
        let generator =
            make_generator(network_id, &[10.0], &[], None, Fees::SenderPays(0), change_address, payment_output.into()).unwrap();

        let pending =
            generator.generate_transaction().unwrap().expect("generator should produce a pending transaction in this scenario");

        let rpc_api_mock = Arc::new(RpcCoreMock::new());
        let rpc: Arc<DynRpcApi> = rpc_api_mock;

        // First call can fail (mock RPC) but must not panic.
        let _ = pending.try_submit(&rpc).await;

        // Second call must return a regular error (not panic).
        let err = pending.try_submit(&rpc).await.expect_err("second submit must be rejected");
        assert!(err.to_string().to_lowercase().contains("multiple"));
        Ok(())
    }
}
